In [1]:
import sklearn

In [2]:
sklearn.__version__ #sk버전 확인

'0.24.2'

In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier #의사결정트리(다른 것에 비해 성능은 떨어짐)
from sklearn.model_selection import train_test_split #훈련, 시험 데이터 분리
import pandas as pd

In [5]:
iris = load_iris() #따로 실행 하기 #앞에서 임포트 안하면 shift+tab 설명 안나옴

In [13]:
#iris필수 확인
type(iris) #dic인지 뭔지 확인 bunch=dic
iris['data'] #dic 형태인 데이터 확인
iris.keys() #키값 알아내기
iris['target'] #키값 중 하나 확인하기
iris['target_names'] #키값 중 하나 확인하기
iris['feature_names'] #키값 중 하나 확인하기

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [14]:
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names) #데이터프레임으로 만들기
iris_df.head(2) #x축index, y축col, 채워진 값 values

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2

In [66]:
iris_df['label']=iris.target #데이터프레임에 레이블까지 넣어서 만들기
iris_df.sample(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
86                6.7               3.1                4.7               1.5   
46                5.1               3.8                1.6               0.2   

    lable  label  
86      1      1  
46      0      0

In [22]:
X_train,X_test,y_train,y_test = train_test_split(iris.data, #X
                                                 iris.target, #y
                                                test_size=0.2, #test20%, train80%
                                                random_state=11) #줄 안나눠지면 앞에 \쓰면 됨

In [23]:
X_train.shape, X_test.shape

((120, 4), (30, 4))

In [24]:
X_test, y_test

(array([[6.8, 3. , 5.5, 2.1],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.8, 5.1, 1.5],
        [6.3, 3.3, 4.7, 1.6],
        [6.4, 2.7, 5.3, 1.9],
        [4.9, 3.1, 1.5, 0.1],
        [6.7, 3.1, 4.4, 1.4],
        [5.7, 4.4, 1.5, 0.4],
        [4.8, 3.1, 1.6, 0.2],
        [6.1, 2.9, 4.7, 1.4],
        [6. , 2.2, 5. , 1.5],
        [6. , 2.2, 4. , 1. ],
        [5.4, 3. , 4.5, 1.5],
        [5.7, 2.5, 5. , 2. ],
        [6.9, 3.1, 5.4, 2.1],
        [4.5, 2.3, 1.3, 0.3],
        [6.3, 2.9, 5.6, 1.8],
        [5.6, 3. , 4.5, 1.5],
        [6.5, 3.2, 5.1, 2. ],
        [5.8, 2.7, 5.1, 1.9],
        [5.6, 2.5, 3.9, 1.1],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.6, 1. , 0.2],
        [6.4, 3.2, 4.5, 1.5],
        [4.8, 3. , 1.4, 0.1],
        [4.8, 3.4, 1.6, 0.2],
        [5.9, 3. , 5.1, 1.8],
        [6.6, 3. , 4.4, 1.4],
        [5.4, 3.9, 1.3, 0.4],
        [6. , 3.4, 4.5, 1.6]]),
 array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
        0, 1, 0, 0, 2, 1

In [25]:
#모델생성
dt_clf = DecisionTreeClassifier(random_state=11) #하이퍼파라미터: ML, DL에서 모델링할 때 사용자가 직접 세팅해주는 값

In [27]:
#학습
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [28]:
#평가, 예측
pred = dt_clf.predict(X_test)

In [32]:
#학습됐는지 평가
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)*100 #93% >> 100개 중 93개는 맞춤

93.33333333333333

In [33]:
#학습/시험 데이터 세트 분리 없이 하면 : 같은데이터로 학습하고 검정하면 100%가 나옴. 다른데이터로 검증해야 학습됐는지 측정가능.

In [35]:
iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_lable = iris.target
dt_clf.fit(train_data,train_lable)

DecisionTreeClassifier()

In [36]:
pred = dt_clf.predict(train_data)
accuracy_score(train_lable,pred)

1.0

## K폴드

![](./img/kFold.png)

In [59]:
from sklearn.model_selection import KFold
import numpy as np

In [60]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [61]:
KFold = KFold(n_splits=5,shuffle=True) #비율안따짐
cv_accuracy = []

In [63]:
n_iter = 0
for train_index,test_index in KFold.split(iris.data):
    #print(train_index,test_index)
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'\n{n_iter}교차검증정확도: {accuracy},학습데이터크기:{train_size},검증데이터크기:{test_size}')
    print(f'{n_iter} 검증데이터 인덱스: {test_index}')
    cv_accuracy.append(accuracy)


1교차검증정확도: 0.9,학습데이터크기:120,검증데이터크기:30
1 검증데이터 인덱스: [  3  11  22  24  26  29  31  35  40  48  51  56  69  71  72  76  83  85
  87 111 115 119 121 126 128 130 133 136 142 145]

2교차검증정확도: 0.8667,학습데이터크기:120,검증데이터크기:30
2 검증데이터 인덱스: [  7  16  17  19  34  37  39  47  49  53  57  60  89  91  93  99 101 103
 104 110 118 120 134 135 138 139 143 144 148 149]

3교차검증정확도: 0.9667,학습데이터크기:120,검증데이터크기:30
3 검증데이터 인덱스: [  2   5   6   9  18  21  23  25  28  33  46  62  63  64  66  68  75  77
  80  86  92  94  97 109 114 122 124 125 131 137]

4교차검증정확도: 0.9667,학습데이터크기:120,검증데이터크기:30
4 검증데이터 인덱스: [  4   8  10  15  20  30  36  42  43  45  52  55  61  67  70  78  79  81
  82  96 100 102 105 107 112 117 123 140 141 146]

5교차검증정확도: 0.9333,학습데이터크기:120,검증데이터크기:30
5 검증데이터 인덱스: [  0   1  12  13  14  27  32  38  41  44  50  54  58  59  65  73  74  84
  88  90  95  98 106 108 113 116 127 129 132 147]


In [64]:
np.mean(cv_accuracy)

0.92668

In [67]:
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [68]:
from sklearn.model_selection import StratifiedKFold

In [69]:
skf = StratifiedKFold(n_splits=3)
n_iter=0
for train_index,test_index in skf.split(iris_df,iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(n_iter)
    print('학습\n',label_train.value_counts())
    print('검증\n',label_test.value_counts())
    print('-'*20)

1
학습
 2    34
0    33
1    33
Name: label, dtype: int64
검증
 0    17
1    17
2    16
Name: label, dtype: int64
--------------------
2
학습
 1    34
0    33
2    33
Name: label, dtype: int64
검증
 0    17
2    17
1    16
Name: label, dtype: int64
--------------------
3
학습
 0    34
1    33
2    33
Name: label, dtype: int64
검증
 1    17
2    17
0    16
Name: label, dtype: int64
--------------------


In [70]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)


sKfold = StratifiedKFold(n_splits=3,shuffle=True) #비율따짐
cv_accuracy = []
n_iter = 0
for train_index,test_index in KFold.split(iris.data):
    #print(train_index,test_index)
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'\n{n_iter}교차검증정확도: {accuracy},학습데이터크기:{train_size},검증데이터크기:{test_size}')
    print(f'{n_iter} 검증데이터 인덱스: {test_index}')
    cv_accuracy.append(accuracy)


1교차검증정확도: 0.9333,학습데이터크기:120,검증데이터크기:30
1 검증데이터 인덱스: [  6   9  28  32  37  43  48  49  53  57  59  64  70  72  75  76  79  91
 103 105 108 109 110 122 125 131 133 135 139 149]

2교차검증정확도: 0.9333,학습데이터크기:120,검증데이터크기:30
2 검증데이터 인덱스: [  3  10  11  13  24  38  40  46  65  66  68  73  74  77  78  83  85  87
  89  90  94  95 100 104 113 117 118 120 130 140]

3교차검증정확도: 1.0,학습데이터크기:120,검증데이터크기:30
3 검증데이터 인덱스: [  0   1   2   5  16  26  27  35  42  51  55  61  67  71  80  81  82  86
  97 111 112 114 115 116 121 126 128 136 137 147]

4교차검증정확도: 0.9,학습데이터크기:120,검증데이터크기:30
4 검증데이터 인덱스: [  7  12  14  18  19  20  23  29  30  39  47  50  52  54  56  60  84  92
  93 102 106 119 124 127 129 132 134 141 144 145]

5교차검증정확도: 0.9667,학습데이터크기:120,검증데이터크기:30
5 검증데이터 인덱스: [  4   8  15  17  21  22  25  31  33  34  36  41  44  45  58  62  63  69
  88  96  98  99 101 107 123 138 142 143 146 148]


In [71]:
from sklearn.model_selection import cross_val_score

In [72]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [73]:
cross_val_score(dt_clf,iris.data,iris.target,scoring='accuracy',cv=3)

array([0.98, 0.94, 0.98])

In [75]:
grid_parameters = { 'max_depth':[1,2,3],
                  'min_samples_split':[2,3]}

In [77]:
iris = load_iris()
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                                                iris.target,
                                                test_size=0.2,
                                                random_state=121)
dt_clf = DecisionTreeClassifier()

In [78]:
from sklearn.model_selection import GridSearchCV
grid_dtree = GridSearchCV(dt_clf,param_grid=grid_parameters,cv=3,refit=True)

In [79]:
grid_dtree.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [80]:
grid_dtree.cv_results_

{'mean_fit_time': array([0.00066471, 0.        , 0.00033236, 0.00033243, 0.00066487,
        0.00033259]),
 'std_fit_time': array([0.00047002, 0.        , 0.00047002, 0.00047013, 0.00047013,
        0.00047036]),
 'mean_score_time': array([0.        , 0.00033243, 0.00033259, 0.00033243, 0.        ,
        0.        ]),
 'std_score_time': array([0.        , 0.00047013, 0.00047036, 0.00047013, 0.        ,
        0.        ]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_samples_split': 3},
  {'max_depth': 3, 'min_sample

In [81]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [82]:
scoreds_df = pd.DataFrame(grid_dtree.cv_results_)
scoreds_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.000665       0.00047         0.000000         0.00000   
1       0.000000       0.00000         0.000332         0.00047   
2       0.000332       0.00047         0.000333         0.00047   
3       0.000332       0.00047         0.000332         0.00047   
4       0.000665       0.00047         0.000000         0.00000   
5       0.000333       0.00047         0.000000         0.00000   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}              0.700   
1  {'max_depth': 1, 'min_samples_split': 3}              0.700   
2  {'max_depth': 2, 'min_samples_split': 2}              0.925   
3  {'max_depth': 2, 'min_samples_split': 3}              0.925   
4  {'max_depth': 3, 'min_samples_split': 2}              0.975   
5  {'max_depth': 3, 'min_samples_split': 3}              0.975   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                0.7               0.70         0.700000    1.110223e-16   
1                0.7               0.70         0.700000    1.110223e-16   
2                1.0               0.95         0.958333    3.118048e-02   
3                1.0               0.95         0.958333    3.118048e-02   
4                1.0               0.95         0.975000    2.041241e-02   
5                1.0               0.95         0.975000    2.041241e-02   

   rank_test_score  
0                5  
1                5  
2                3  
3                3  
4                1  
5                1

In [83]:
scoreds_df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [86]:
scoreds_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

## 레이블 인코딩

In [87]:
from sklearn.preprocessing import LabelEncoder

In [88]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [89]:
encoder.classes_ #0~5

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [91]:
encoder.inverse_transform([0,2,4,5,]) #7도 넣으면 에러남

array(['TV', '믹서', '전자레인지', '컴퓨터'], dtype='<U5')

In [92]:
from sklearn.preprocessing import OneHotEncoder

In [98]:
#숫자로 바꾸기
items
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels = labels.reshape(-1,1)
labels
oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [99]:
oh_labels.shape

(8, 6)

In [104]:
import pandas as pd
df = pd.DataFrame({'item':['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터']})
df

item
0     TV
1    냉장고
2     믹서
3    선풍기
4  전자레인지
5    컴퓨터

In [105]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        1         0           0         0
3        0         0        0         1           0         0
4        0         0        0         0           1         0
5        0         0        0         0           0         1

In [106]:
iris = load_iris()

In [107]:
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names) #방금 위에거 실행안하면 탭 눌러도 자동 완성 안됨

In [109]:
iris_df.mean()
iris_df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [110]:
from sklearn.preprocessing import StandardScaler

In [111]:
scaler = StandardScaler()

In [112]:
iris_scaled = scaler.fit_transform(iris_df)

In [113]:
iris_df_scaled = pd.DataFrame(data = iris_scaled,columns=iris.feature_names)

In [115]:
iris_df_scaled.mean()
iris_df_scaled.var()

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [116]:
from sklearn.preprocessing import MinMaxScaler

In [117]:
scaler = MinMaxScaler()

In [120]:
iris_scaled = scaler.fit_transform(iris_df)
iris_df_scaled = pd.DataFrame(data = iris_scaled,columns=iris.feature_names)
iris_df.mean(),iris_df.max()

(sepal length (cm)    5.843333
 sepal width (cm)     3.057333
 petal length (cm)    3.758000
 petal width (cm)     1.199333
 dtype: float64,
 sepal length (cm)    7.9
 sepal width (cm)     4.4
 petal length (cm)    6.9
 petal width (cm)     2.5
 dtype: float64)

In [121]:
iris_df_scaled.min(),iris_df_scaled.max()

(sepal length (cm)    0.0
 sepal width (cm)     0.0
 petal length (cm)    0.0
 petal width (cm)     0.0
 dtype: float64,
 sepal length (cm)    1.0
 sepal width (cm)     1.0
 petal length (cm)    1.0
 petal width (cm)     1.0
 dtype: float64)

In [122]:
train_array = np.arange(11).reshape(-1,1)
test_array = np.arange(6).reshape(-1,1)

In [126]:
train_array
test_array
scaler = MinMaxScaler()
scaler.fit(train_array) #학습할 때는 전체 데이터가 들어가야
scaler.transform(train_array) #트랜스폼은 부분데이터 들어가도 상관없음
scaler.transform(test_array)

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5]])